#!/bin/bash
# $Id$
#
# =============================================================================
# Simple Database Analysis Report (c) 2003-2004 by IzzySoft (devel@izzysoft.de)
# -----------------------------------------------------------------------------
# This report script creates a HTML document containing an overview on the
# database, whichs SID you either provide at the command line or configure it
# in the block below. But more than this, it not only reads the usual
# performance indicators out of the usual views, but connects values and gives
# you hints about how to use these results.
# I'ld never claim this report tool to be perfect, complete or "state of the
# art". But it's simple to use and very helpful to those not having a license
# to the expensive AddOns available at Oracle. Any hints on errors or bugs as
# well as recommendations for additions are always welcome.
#                                                              Itzchak Rehberg
# -----------------------------------------------------------------------------
# This is the config file - and the only one you need to edit!
#
# =================================================[ Configuration Section ]===
# --------------------------------------------------[ Database Information ]---
# SID of the database to analyse
export ORACLE_SID=$1
# login information
user=sys
password="nis!"

# -------------------------------------------------[ Files and Directories ]---
# directory for temporary files
TMPDIR=/tmp
# in which directory should the report ($ORACLE_SID.html) be placed
REPDIR=/tools/oracle/app/product/9.2.0/dba_admin/orarep/reports
# StyleSheet to use
CSS=iceage.css

# --------------------------------------------------------------[ Warnings ]---
# At what treshholds we should issue warnings (yellow background). TPH_* stands
# for Timeouts Per Hour, WHP_* for Waits Per Hour. Values to specify are
# NUMBERs, i.e. decimals are permitted as well as fractions
# No logfile available to switch to
TPH_NOLOG=5/6
WPH_NOLOG=5.5
# Ratios: WR_* is the Warning ratio, AR_* the Alert ratio.
# Buffer Pool Ratio
WR_IE_BUFFNW=80
AR_IE_BUFFNW=60
WR_IE_REDONW=90
AR_IE_REDONW=75
WR_IE_BUFFHIT=50
AR_IE_BUFFHIT=30
WR_IE_IMSORT=85
AR_IE_IMSORT=70
WR_IE_LIBHIT=80
AR_IE_LIBHIT=60
WR_IE_SOFTPRS=80
AR_IE_SOFTPRS=60
WR_IE_LAHIT=85
AR_IE_LAHIT=70
WR_IE_PRSC2E=80
AR_IE_PRSC2E=60
WR_BUFF=0.7
AR_BUFF=0.9
# non-autoextensible datafile filled x %
WR_FILEUSED=85
AR_FILEUSED=95
WR_RWP=20
AR_RWP=30

# -------------------------------------------------------------------[ SQL ]---
# Top settings: Display Top N Statements
TOP_N_WAITS=10
TOP_N_TABLES=10

# --------------------------------------------------------------[ Features ]---
# Include User Information segment? [0|1]
MK_USER=0
# Include DBLink Information table? [0|1]
MK_DBLINK=0
# Include Resource Plan Report? [0|1]
MK_RSRC=0
# Include DBA Profiles? [0|1]
MK_DBAPROF=0
# Include Instance Efficiency? [0|1]
MK_INSTEFF=1
# Include Load Profile? [0|1]
MK_LOADPROF=1
# Include table statistics? [0|1]
MK_TABS=1
# Include TableSpace Quotas? [0|1]
MK_TSQUOT=0
# Include DataFile Stats? [0|1]
MK_FILES=1
# Include the DBWR statistics? [0|1]
MK_DBWR=1
# Include LGWR statistics? [0|1]
MK_LGWR=1
# Include Rollback Segment Stats (maybe unnecessary w/ Auto Undo)? [0|1]
MK_RBS=0
# Include the "Memory Values" block? [0|1]
MK_MEMVAL=0
# Include Common Pool Stats block? [0|1]
MK_POOL=1
# Include the Buffer Ratios? [0|1]
MK_BUFFRAT=1
# Include the SysStat Info segment? [0|1]
MK_SYSSTAT=0
# Include the Selected WaitEvents segment? [0|1]
MK_WTEVT=1
# Include FreeListContention (possible affected tables)? [0|1]
MK_FLC=1
# Include Enqueue Waits (Oracle 9i and higher only)? [0|1]
MK_ENQ=1
# Include Undo Segment Statistics (Oracle 9i+)? [0|1]
MK_USS=1
MK_USSTAT=0
# Include the Invalid Objects segment? [0|1]
MK_INVOBJ=1
# Include the TableScan stats? [0|1]
MK_TSCAN=1
# Include the list of TOP_N tables that need more extents? [0|1]
MK_NEXT=0
# ===================================================================[ EOF ]===
