<HTML><HEAD>
 <META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-15"/>
 <LINK REL='stylesheet' TYPE='text/css' HREF='../{css}'/>
 <TITLE>OraHelp: Resource Plan Directives</TITLE>
</HEAD><BODY>

<TABLE WIDTH="95%" ALIGN="center"><TR><TD>
 <H3>Resource Plan Directives</H3>
 <P>This table lists up the resource plan directives for consumer groups only.
  Although most column names are self-explaining, one word on the CPU columns:
  Within one plan, first the group with Prio 1 is served and receives all CPU
  it needs up to the percentage set in this column. From the leftover, the same
  procedure is repeated for Prio 2 and so on. This means, all values for a
  given plan and a given Prio should sum up to max. 100, while the value for a
  given plan and all Prios can (and in most cases should) sum up to more than
  100.</P>

 <H3>New columns with Oracle 9i</H3>
 <P>With Oracle 9i, this facility improved and new capabilities have been added.
  As a result, there are some more columns available and displayed by OraRep for
  Oracle Databases version 9 and up:</P>
 <TABLE ALIGN="center" BORDER="1">
  <TR><TH CLASS="th_sub">Column</TH><TH CLASS="th_sub">Description</TH></TR>
  <TR><TD CLASS="td_name">Sess</TD><TD>Specifies maximum number of concurrently
      active sessions for a consumer group</TD></TR>
  <TR><TD CLASS="td_name">Queue</TD><TD>Specified time (in seconds) after which
      a job in the execution queue (waiting for execution) will timeout</TD></TR>
  <TR><TD CLASS="td_name">SwGrp</TD><TD>Specifies consumer group to which this
      session is switched if other switch criteria is met</TD></TR>
  <TR><TD CLASS="td_name">SwTime</TD><TD>Specifies time (in seconds) that a
      session can execute before it is switched to another consumer group</TD></TR>
  <TR><TD CLASS="td_name">SesTO</TD><TD>Specifies the maximum execution time
      (in seconds) allowed for a session</TD></TR>
  <TR><TD CLASS="td_name">Undo</TD><TD>Sets a maximum in kilobytes (K) on the
      total amount of undo generated by a consumer group</TD></TR>
 </TABLE>

 <H3>More information</H3>
 <P>For more detailed information on Resource Plans, see the documentation
  shipped with your Oracle Database software in the chapter on "Using the
  Database Resource Manager".</P>
</TD></TR></TABLE>

</BODY></HTML>
